mysql: &mysql
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  pool: 10
  database: hawaii
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *mysql